### PR TITLE
Start splitting display functions into display core

### PR DESCRIPTION
**Pull request by makermelissa**
This starts the restructuring, but also leaves the code functional. There's still a lot more to do and the code is kind of still "under construction", but this is to wrap up the work that I did do with restructuring.

### CODE REVIEW

**Comment by makermelissa** [comment]
I did some basic testing with the BrainCraft and the basic demo script, but nothing extensive, so some additional testing would probably be helpful.

**Review by tannewt — APPROVED** [review]
This all looks good to me. I didn't do any additional testing. Good job refactoring it while keeping it working.

**Comment by makermelissa** [comment]
Thanks

**Comment by FoamyGuy** [comment]
I tested the latest version successfully with Pi 3 B+ and TFT Shield as well as Linux with PyGame Display.

**Comment by makermelissa** [comment]
Awesome, thanks @FoamyGuy.

**Pull request merged**
