### PR TITLE
Revamp Displayio and Add grayscale

### LINKED ISSUE #4: Finish Shapes Supoort
Shapes is currently only extending bitmaps which was enough for the DisplayShapes library to work, but it isn't complete.

### LINKED ISSUE #6: Implement Dirty Rectangle Tracking
This library currently doesn't utilize dirty rectangle tracking, though it has partial implementation. This will speed things up a lot.

### LINKED ISSUE #7: Finish ColorConverter
ColorConverter is partially implemented and will be a big part of ePaper Displays. See #3. This likely could be reworked to make use of Pillow for dithering.

### LINKED ISSUE #32: Display warning for zero width/height bitmap
Waiting on https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/issues/58 to be completed first, so we don't break things. :)

### LINKED ISSUE #36: Remove thread enabling/disabling for autorefresh
I discovered this when working on the Blinka PyPortal library that threads don't like to be started and stopped a bunch, so rather than stopping the thread when turning off autorefresh, it should just make it so the thread "pauses" by not doing anything.

### LINKED ISSUE #54: Add SH1107 display support
There is a parameter missing on the Blinka version of `displayio.Display` specifically `SH1107_addressing`.

```
Traceback (most recent call last):
  File "roomtemp.py", line 41, in configure_display
    display = adafruit_displayio_sh1107.SH1107(display_bus, width=128, height=128)
  File "lib/python3.7/site-packages/adafruit_displayio_sh1107.py", line 73, in __init__
    SH1107_addressing=True,
TypeError: __init__() got an unexpected keyword argument 'SH1107_addressing'
```

The parameter appears to have been renamed from `column_and_page_addressing` in https://github.com/adafruit/circuitpython/commit/06a3d152664a97cc0a2f2faee86d2f5ea4e063e2 which was added in https://github.com/adafruit/circuitpython/commit/f21dc253e094854670b829f6258aac3722eefc26

This renders the [Adafruit_CircuitPython_DisplayIO_SH1107](https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_SH1107) library unusable with Blinka.

My test hardware is the [Pimoroni 1.12" Mono OLED (128x128, white/black) Breakout - I2C](https://shop.pimoroni.com/products/1-12-oled-breakout?variant=29421050757203) on a Raspberry Pi.

PS. I might try to work on a PR, but I don't fully understand the linkage between the C code in adafruit/circuitpython and the Python code in Blinka.

### LINKED ISSUE #94: Change default font to match CircuitPython
Blinka Displayio currently uses the default font provided by PIL, which looks a bit different and is a bit harder to read. According to @tannewt, the font that CircuitPython currently uses is http://terminus-font.sourceforge.net/. I think this should be easy enough to include assuming no license issues.

### LINKED ISSUE #95: SSD1306 displays not working properly
I have a 128x64 display using SSD1306, and it's not working properly.
I noticed that 16384 bytes of data is sent every time, while only 1024 bytes (128 x 64 / 8, 1 bit per pixel) should be sent.
I've read some other issues and I understand that this is a known issue. Creating this issue to help others find it.
Can we add some text to the README file to notify future users that monochrome displays are not supported properly yet?

### LINKED ISSUE #105: SSD1327 lacking grayscale support
Connecting the same SSD1327 display using same library same example

Example:
https://github.com/adafruit/Adafruit_CircuitPython_SSD1327/blob/main/examples/ssd1327_simpletest.py

Guide:
https://learn.adafruit.com/adafruit-grayscale-1-5-128x128-oled-display/circuitpython-wiring-and-usage

CircuitPython on ESP32
image

BLINKA MCP2221A
image

### PR DESCRIPTION
**Pull request by makermelissa**
This change brings Displayio to being much closer in line with the current circuitpython builds, which makes it very accurate, but at this point it is not optimized for running in Python due to some removal of PIL. This adds dirty rectangle tracking as well. I have a bit more testing to do before optimization but it should support monochrome and grayscale OLEDs and allow me to close a number of outstanding issues.

Fixes #105
Fixes #95
Fixes #94
Fixes #54
Fixes #36
Fixes #32
Fixes #7
Fixes #6 
Fixes #4

### CODE REVIEW

**Comment by makermelissa** [comment]
I just tested the SSD1327 and that's now working.
IMG_5375

**Comment by tannewt** [comment]
Feel free to add me as reviewer when it is ready. Thanks for doing this!

**Comment by makermelissa** [comment]
I just tested the SSD1306. It's close, but still needs a little debugging done.
IMG_5377

**Comment by makermelissa** [comment]
Closer...
IMG_5378

**Comment by makermelissa** [comment]
If I had to guess, I'd say it's a row and column offset issue at this point.

**Comment by makermelissa** [comment]
SSD1325 tested good, which is useful since there's currently no Blinka drivers.
IMG_5380

**Comment by makermelissa** [comment]
SH1107 isn't super close, but maybe if I can get that working, the SSD1306 will work...
IMG_5382

**Comment by makermelissa** [comment]
Apparently it helps if you use the correct test script.
IMG_5383

**Comment by makermelissa** [comment]
I'm going to fix the SSD1306 and I think the PR will be ready at that point. The other possibility is that it's throwing some garbage to the display prior to writing as the right side of the rectangle does wrap to the left side.

**Comment by makermelissa** [comment]
The numbers were looking correct, so I decided to compare byte for byte what was being sent to the display. Here's the place where it differs between blinka and cp:
missing bytes

The bytes circled in red are not being sent, but the green ones are, which happens in the core's set_region_to_update() function, which is what I suspected. I think those are the command bytes that are missing.

**Comment by makermelissa** [comment]
Much better
IMG_5385

**Comment by makermelissa** [comment]
@FoamyGuy I added you as a reviewer since this change will likely affect https://github.com/FoamyGuy/Blinka_Displayio_PyGameDisplay since some of the "protected" functions have been renamed to match the ones used in the core.

The plan is to release this as 1.0.0 after this PR is merged, so it will be a new major version anyways.

**Review by tannewt — APPROVED** [review]
Great work on this! Didn't see anything that needs updating. Thank you so much for doing this porting.

**Comment by makermelissa** [comment]
You're welcome. I think I found one more bug that needs fixing first.

**Pull request merged**
