### PR TITLE
Update to CircuitPython 9.0.0 API

### LINKED ISSUE #120: Update any changed APIs now that CircuitPython 9.0.0 has been released
See https://github.com/adafruit/circuitpython/issues?q=milestone%3A9.0.0+label%3Adisplayio+label%3A%22breaks+api%22

Also https://github.com/adafruit/circuitpython/pull/8456

### PR DESCRIPTION
**Pull request by makermelissa**
Fixes #120. Tested successfully with an ST7789 TFT, SSD1680 eInk, and SSD1306 mono display via I2C. Also adds release drafter.

### CODE REVIEW

**Review by dhalbert — COMMENTED** [review]
Just as background:

Right now CircuitPython 9.0.0 supports old and new namings, though with warnings. 

We have not yet converted over libraries in an incompatible way, and we are still building 8.x bundles. When we stop building 8.x bundles, we will put a "last available 8.x bundle" link here: https://learn.adafruit.com/welcome-to-circuitpython/frequently-asked-questions#faq-3105289. We will wait a bit (a few weeks, I think) before stopping the bundles.

In the display libraries, most of the naming differences are only in the examples. Right now they are written to be both 8.x and 9.x compatible. When we stop building the 8.x bundles, we can remove the compatibility code.

Would you want to wait until then before merging this? I'm not sure who uses this and cares. Anyone who updates this library is going to have to change their code over, but maybe that's fine. If they're not ready they'll just use the previous major version.

**Comment by makermelissa** [comment]
I think it's fine to merge. My plan was to release as 2.0.0 because of the different API.

**Comment by dhalbert** [comment]
@tannewt just asking you to check the naming, since you know it well

**Review by tannewt — APPROVED** [review]
Looks right to me! Thanks for the update!

**Pull request merged**
