### PR TITLE
Convert the parameters for Image.resize from TileGrid to integers

### LINKED ISSUE #47: Changing the scale of a TileGrid's parent can cause a crash
Changing the scale of the parent of a TileGrid **after** it has been added to the parent causes a crash.

The following test file demonstrates
[test_change_scale_on_a_tilegrid_parent.py](https://github.com/adafruit/Adafruit_Blinka_Displayio/files/5975931/test_change_scale_on_a_tilegrid_parent.py.txt)

And produces
```
python .\test_change_scale_on_a_tilegrid_parent.py
pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File ".\test_change_scale_on_a_tilegrid_parent.py", line 38, in <module>
    display.refresh()
  File ".\lib\site-packages\blinka_displayio_pygamedisplay.py", line 113, in refresh
    self._current_group._fill_area(
  File ".\lib\site-packages\displayio\group.py", line 162, in _fill_area
    layer._fill_area(buffer)  # pylint: disable=protected-access
  File ".\lib\site-packages\displayio\tilegrid.py", line 271, in _fill_area
    image = image.resize(
  File ".\lib\site-packages\PIL\Image.py", line 1913, in resize
    im = im.resize(size, resample, box)
  File ".\lib\site-packages\PIL\Image.py", line 1935, in resize
    return self._new(self.im.resize(size, resample, box))
TypeError: integer argument expected, got float
```

The cause is PIL expecting integers to be passed in from tilegrid.py:line 271

### PR DESCRIPTION
**Pull request by lesamouraipourpre**
This should fix #47.

### CODE REVIEW

**Comment by lesamouraipourpre** [comment]
Black is passing at my end (Windows 10), so I'm not sure what to change to pass CI.
black

**Comment by makermelissa** [comment]
I think once #49 gets merged in, this will likely pass.

**Comment by makermelissa** [comment]
If you pull in the latest changes and push to your repo, it should now pass.

**Review by makermelissa — APPROVED** [review]
Thank you

**Pull request merged**
