### PR TITLE
initial implementation of I2CDisplay class

### LINKED ISSUE #2: Add I2C Display support

### PR DESCRIPTION
**Pull request by eteq**
If this actually works, I think it closes #2  ... I basically followed the `fourwire` class interface.  I then tested it on a 128x64 SSD1306 based OLED (https://www.adafruit.com/product/326), and while it does sucessfully talk to the OLED and do things like command the OLED on/off based on the init string, it's just blinking gibberish when I run any regular `displayio` code.  So I'm not confident this PR is actually right, hence the "draft" status.

That said, it's probably better than nothing!  And maybe I did something obviously wrong someone can point out to me to correct it?

### CODE REVIEW

**Review by makermelissa — CHANGES_REQUESTED** [review]
I notice you changed the send function parameters. They should match CircuitPython. See https://circuitpython.readthedocs.io/en/latest/shared-bindings/displayio/#displayio.I2CDisplay

**Comment by wolfmanjm** [comment]
I have implemented the I2CDisplay class, based on this but fixed some of the issues based on the C version of I2CDisplay in CP.
The code is here https://github.com/wolfmanjm/Adafruit_Blinka_Displayio/blob/implement/I2CDisplay/displayio/i2cdisplay.py but I am unsure as to how to update this PR, or should I provide a new PR?

I have been unable to test it though as I have an SSD1306, and there is currently no support for monochrome displays in ColorConverter and maybe some other parts of Blinka Displayio. The I2C transactions do appear to work though based on looking at a logic analyzer trace, and the SSD1306 appears to be setup correctly. I do not have an I2C color display that would be supported, the only one I have is the ST7789 which is SPI and works nicely.

**Comment by makermelissa** [comment]
Hi, really sorry for the long delay in getting back to you. I just took a look at the link in your last comment and see the note:
```
 # NOTE: we have to have a toggle_every_byte parameter, which we ignore,
 # because Display._write() sets it regardless of bus type.
```
This is a really good point. I'm going to see if there's a better solution and if not I can approve. As for your question, just push your changes and the PR should automatically update. No need to submit a new one because it just shows the differences between the branch you are pulling from and the one you're pushing to.

**Comment by makermelissa** [comment]
Ok, after looking at the displayio code for circuitpython, I'm going to agree with this strategy. Basically in CircuitPython,. the public function doesn't have this parameter, but the private one does. Since this implementation doesn't really distinguish the two, this is a good approach.

**Comment by wolfmanjm** [comment]
FYI this is not my PR and I cannot push to it. However this https://github.com/lesamouraipourpre/Adafruit_Blinka_Displayio/commit/94342b1947ee2913c581317d280d9dab4e85f374 link appears to have combined my changes and has tested it as well. I suggest that the author of that submit a new PR and this one be closed.

**Comment by makermelissa** [comment]
@wolfmanjm I'm going to try and get this PR passing and merged. If you'd like to piggyback on top afterwards, I think that would work great.

**Comment by wolfmanjm** [comment]
This PR is totally incorrect BTW and does not work.

**Comment by makermelissa** [comment]
Thanks @wolfmanjm. @lesamouraipourpre want to submit a PR to implement this?

**Comment by makermelissa** [comment]
Closing in favor of #58.

**Pull request closed without merging**
