### PR TITLE
Add vectorio support

### LINKED ISSUE #117: Add Vectorio Support
Code will likely be adapted from code by @lesamouraipourpre in #71 as a base.

### PR DESCRIPTION
**Pull request by makermelissa**
Fixes #117.

### CODE REVIEW

**Review by FoamyGuy — COMMENTED** [review]
Do we need to add `vectorio` here in pyproject.toml? https://github.com/adafruit/Adafruit_Blinka_Displayio/blob/0c50ba211cab59828f683daebd47facd58ccca40/pyproject.toml#L45

The first time I tried testing this I got an error on the vectorio import internally in Blinka_DisplayIO. I added this and it seemed to resolve it. But then I tried to go back with it the original way to recreate the exact stacktrace and now I'm not having the same outcome any more. Perhaps I did something wrong when I installed it initially. 

It might be good to keep pyprojet.toml and setup.py in sync even if it isn't required for all contexts as well though.

**Comment by FoamyGuy** [comment]
The functionality and code look good to me. I tested it successfully with vectorio example code from the docs and PyGameDisplay library.

**Comment by makermelissa** [comment]
> Do we need to add `vectorio` here in pyproject.toml?

Yes, I believe so.

**Review by FoamyGuy — APPROVED** [review]
Looks good to me. Thanks for the addition!

**Pull request merged**
