### PR TITLE
Remove setup.py in favor of pyproject.toml

### PR DESCRIPTION
**Pull request by makermelissa**

### CODE REVIEW

**Comment by dhalbert** [comment]
Were you able to test the PyPi install on a board with Python 3.7 installed?

**Review by tekktrik — APPROVED** [review]

**Comment by makermelissa** [comment]
Hmm, I'm not sure if this works on Python 3.7. I'm also not sure I did it correctly. Here's what I tried:

1. Made sure Python 3.7 was the latest.
2. Made sure pip3 corresponded to the latest python.
3. Copied entire Displayio folder to home directory
4. Inside of folder, ran `pip3 install -e .`
5. Received error **Directory '.' is not installable. File 'setup.py' not found.**

**Comment by makermelissa** [comment]
However, PlatformDetect (which doesn't have a setup.py file) installs just fine. So it probably just can't be installed in the manner I tried.

**Comment by tekktrik** [comment]
You might need to upgrade pip, I can't remember if that can cause the error you got.

**Comment by makermelissa** [comment]
Oh yep, you're correct. I was running Pip version 9. Upgrading to latest fixed it. It still worked fine with PyPI and PlatformDetect even on the older version, so I'm comfortable with this change.

**Review by dhalbert — APPROVED** [review]
> Oh yep, you're correct. I was running Pip version 9. Upgrading to latest fixed it. It still worked fine with PyPI and PlatformDetect even on the older version, so I'm comfortable with this change.

:+1:

**Pull request merged**
